[profile.default]
src = "src/main/solidity"
out = "build/contracts"
libs = ["lib"]
test = "src/test/solidity"
script = "src/main/solidity/script"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.26"

# Base network configuration
[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_SEPOLIA_API_KEY}" }

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000 }

[profile.lite]
optimizer = false