apiVersion: apps/v1
kind: Deployment
metadata:
  name: attestor
  namespace: staging
  labels:
    app: attestor
    environment: staging
    network: base-sepolia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attestor
      environment: staging
  template:
    metadata:
      labels:
        app: attestor
        environment: staging
        network: base-sepolia
    spec:
      containers:
      - name: attestor
        image: allenday/attestor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - secretRef:
            name: attestor-secrets
        - secretRef:
            name: attestor-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
      restartPolicy: Always