apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eas-validator-secrets
  namespace: staging
  labels:
    app: eas-validator
    environment: staging
spec:
  secretStoreRef:
    name: bitwarden-secretstore
    kind: SecretStore
  target:
    name: eas-validator-secrets
  data:
  - secretKey: DEPLOY_CLOUD_STAGING_VALIDATOR_PRIVATE_KEY
    remoteRef:
      key: "c9b90f92-2146-4469-bfd4-b33a0137dd76"
  - secretKey: DEPLOY_CLOUD_STAGING_VALIDATOR_PUBLIC_ADDRESS
    remoteRef:
      key: "bbcb4750-831f-4731-b1cd-b33a0138895c"
---
apiVersion: v1
kind: Secret
metadata:
  name: eas-validator-config
  namespace: staging
  labels:
    app: eas-validator
    environment: staging
type: Opaque
stringData:
  # Environment configuration
  NODE_ENV: "staging"
  LOG_LEVEL: "debug"
  NETWORK: "base-sepolia"