apiVersion: apps/v1
kind: Deployment
metadata:
  name: eas-validator
  namespace: production
  labels:
    app: eas-validator
    environment: production
    network: base-mainnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eas-validator
      environment: production
  template:
    metadata:
      labels:
        app: eas-validator
        environment: production
        network: base-mainnet
    spec:
      containers:
      - name: eas-validator
        image: allenday/eas-validator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - secretRef:
            name: eas-validator-secrets
        - secretRef:
            name: eas-validator-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
      restartPolicy: Always