apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eas-validator-production
  namespace: production
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - eas.airitual.ai  # Replace with your production domain
    secretName: production-tls
  rules:
  - host: eas.airitual.ai  # Replace with your production domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eas-validator
            port:
              number: 80