apiVersion: v1
kind: Service
metadata:
  name: attestor
  namespace: production
  labels:
    app: attestor
    environment: production
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: attestor
    environment: production