version: '3.8'

services:
  validator:
    build:
      context: ../../../src/main/typescript/validator
      dockerfile: Dockerfile
    image: eas-validator:prod
    container_name: eas-validator-prod
    ports:
      - "8080:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - NETWORK=CLOUD
      - ENVIRONMENT=PROD
      - COMPONENT=VALIDATOR
      - CONCERN=DEPLOY
    env_file:
      - ../../../src/main/typescript/validator/.env.prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - eas-network
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  dapp:
    image: nginx:alpine
    container_name: eas-dapp-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../../build/html/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      validator:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - eas-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M

networks:
  eas-network:
    driver: bridge