name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    strategy:
      fail-fast: true

    name: Validator service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run health checks
        run: task doctor
        id: doctor

      - name: Run build
        run: task app:build
        id: build

      - name: Run tests
        run: task app:test:typescript
        id: test