name: Deploy Contracts

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network to deploy to'
        required: true
        default: 'sepolia'
        type: choice
        options:
        - sepolia
        - mainnet

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.network }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup environment
        run: |
          if [ "${{ github.event.inputs.network }}" = "mainnet" ]; then
            echo "RPC_URL=${{ secrets.BASE_MAINNET_RPC_URL }}" >> $GITHUB_ENV
            echo "ETHERSCAN_API_KEY=${{ secrets.BASESCAN_API_KEY }}" >> $GITHUB_ENV
          else
            echo "RPC_URL=${{ secrets.BASE_SEPOLIA_RPC_URL }}" >> $GITHUB_ENV
            echo "ETHERSCAN_API_KEY=${{ secrets.BASESCAN_SEPOLIA_API_KEY }}" >> $GITHUB_ENV
          fi

      - name: Deploy contracts
        run: |
          forge script src/solidity/script/Deploy.s.sol:DeployScript \
            --rpc-url $RPC_URL \
            --private-key ${{ secrets.DEPLOY_PRIVATE_KEY }} \
            --broadcast \
            --verify
        env:
          BASESCAN_API_KEY: ${{ env.ETHERSCAN_API_KEY }}

      - name: Save deployment artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deployment-${{ github.event.inputs.network }}
          path: |
            broadcast/
            out/