name: Publish Static Site

on:
  push:
    branches: [ main ]
    paths:
      - 'src/main/html/**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup dependencies
        run: npm install

      - name: Install BWS CLI
        run: |
          wget -O bws.zip "https://github.com/bitwarden/sdk-sm/releases/download/bws-v1.0.0/bws-x86_64-unknown-linux-gnu-1.0.0.zip"
          unzip bws.zip
          sudo chmod +x bws
          sudo mv bws /usr/local/bin/
          rm bws.zip

      - name: Build site
        env:
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
          BWS_PROJECT_ID: ${{ secrets.BWS_PROJECT_ID }}
        run: |
          # For GitHub Pages, use the Kubernetes production validator endpoint
          EAS_VALIDATOR_URL="https://attestor.cyberstorm.dev"
          echo "🔧 Using Kubernetes validator URL: $EAS_VALIDATOR_URL"
          export EAS_VALIDATOR_URL
          
          task app:build
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/html/dist
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4